### ISSUE TITLE
customizing issues 

### ISSUE THREAD

**Issue by frispete** [jitsi/docker-jitsi-meet#1185] opened 2022-01-03 16:01 UTC
In former times, it was possible to tweak an installation by providing some scripts/files in `module/rootfs`, eg. `web/rootfs`.
This seems to be not working anymore, neither with stable-6726-1 nor with latest. 

I used to add a script `web/rootfs/etc/cont-init.d/20-custom`, starting with:
```
#!/usr/bin/with-contenv bash

# apply some tweaks here
```
but this file isn't appearing in the container after build. Also the content seems to differ between `web/rootfs/etc/cont-init.d`:
```
server:/srv/docker-jitsi-meet# l web/rootfs/etc/cont-init.d/
total 8
drwxrwxr-x 2 root root   38 Jan  2 18:12 ./
drwxrwxr-x 4 root root   43 Jan  2 18:12 ../
-rw-rw-r-- 1 root root 3296 Dec 14 10:04 10-config
-rw-rw-r-- 1 root root  353 Jan  2 13:17 20-custom
```
and the container:
```
root@da61ea02178b:/# ls -la /etc/cont-init.d/            
total 8
drwxrwxr-x 1 root root   46 Dec 14 10:04 .
drwxrwxr-x 1 root root   97 Jan  3 16:37 ..
-rw-rw-r-- 1 root root    0 Dec 14 10:04 .gitkeep
-rwxr-xr-x 1 root root  267 Dec 14 10:04 01-set-timezone
-rwxr-xr-x 1 root root 3296 Dec 14 10:04 10-config
```

Same behavior is observed with some arbitrary files added in `web/rootfs/usr/share/jitsi-meet/images`. 

They also don't show up in the final container. The `web/Dockerfile` implies, that this should work:
```
[...]
COPY rootfs/ /
[...]
```

Any idea, why these files aren't picked up here?

**Comment by saghul** [comment] 2022-01-04 10:40
How are you rebuilding the image?

We've made no change to prevent that behavior.

**Comment by frispete** [comment] 2022-01-04 12:47
Hmm, thanks @saghul for that info.

I've started with:
```
docker-compose -f docker-compose.yml -f jigasi.yml -f jibri.yml -f etherpad.yml up -d
```
inside the downloaded release tarball after adding `20-custom` and some other files. The changes were not picked up. Then I changed the yaml files to  fetch the latest, and the images reflect that:
```
# docker image ls
REPOSITORY            TAG                 IMAGE ID       CREATED         SIZE
jitsi/jibri           latest              3177bb40ad84   43 hours ago    1.27GB
jitsi/jigasi          latest              42cb38d714ff   43 hours ago    341MB
jitsi/jvb             latest              e12630c40b63   43 hours ago    419MB
jitsi/jicofo          latest              715e4192452a   43 hours ago    374MB
jitsi/web             latest              701fb5e1716c   43 hours ago    262MB
jitsi/base-java       latest              050745e787a0   43 hours ago    325MB
jitsi/base            latest              61af96893e86   43 hours ago    115MB
debian                bullseye-slim       8bca477113bd   2 weeks ago     80.4MB
jitsi/prosody         latest              c92c1374d14c   3 weeks ago     124MB
etherpad/etherpad     1.8.6               b988e1eb0592   15 months ago   309MB
```
as well as the containers:
```
# docker container ls
CONTAINER ID   IMAGE                     COMMAND                  CREATED        STATUS        PORTS                                                                                      NAMES
57735dd285d4   jitsi/jibri:latest        "/init"                  20 hours ago   Up 20 hours                                                                                              docker-jitsi-meet_jibri_1
600480b4b258   jitsi/jvb:latest          "/init"                  20 hours ago   Up 20 hours   0.0.0.0:4443->4443/tcp, :::4443->4443/tcp, 0.0.0.0:10000->10000/udp, :::10000->10000/udp   docker-jitsi-meet_jvb_1
00bdd47fada2   jitsi/jigasi:latest       "/init"                  20 hours ago   Up 20 hours   0.0.0.0:20000-20045->20000-20045/udp, :::20000-20045->20000-20045/udp                      docker-jitsi-meet_jigasi_1
ac3a807e7cd5   jitsi/jicofo:latest       "/init"                  20 hours ago   Up 20 hours                                                                                              docker-jitsi-meet_jicofo_1
da61ea02178b   jitsi/web:latest          "/init"                  20 hours ago   Up 20 hours   0.0.0.0:8008->80/tcp, :::8008->80/tcp, 0.0.0.0:8443->443/tcp, :::8443->443/tcp             docker-jitsi-meet_web_1
178a526cc99b   etherpad/etherpad:1.8.6   "docker-entrypoint.s…"   20 hours ago   Up 20 hours   9001/tcp                                                                                   docker-jitsi-meet_etherpad_1
096edd3470bc   jitsi/prosody:latest      "/init"                  20 hours ago   Up 20 hours   5222/tcp, 5280/tcp, 5347/tcp                                                               docker-jitsi-meet_prosody_1
```

but it doesn't seem to take the changes in the current directories `web,...` into account in the container build step.

My hosts docker and docker-compose are a little aged, though:
```
docker-20.10.6_ce-lp152.2.12.1.x86_64
python3-docker-4.2.0-lp152.1.1.noarch
python3-docker-compose-1.25.1-lp152.1.1.noarch
```
but they did well in setting up jitsi last year.

**Comment by prayagsingh** [comment] 2022-01-04 12:51
@frispete Are you building your own docker images after adding all the changes?

**Comment by prayagsingh** [comment] 2022-01-04 12:58
@frispete It's working fine for me. STEPS I followed.

1. I have created a file `20-config` in `web/rootfs/etc/cont-init.d` directory. 
2. Content of `20-config` is
```
#!/usr/bin/with-contenv bash

echo "Hello Jitsi"
```
3. Created my own docker image.

4. Spin up the containers and below are the logs from the `web` container. Look for `Hello Jitsi`.
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing...
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing...
using keys found in /config/keys
[cont-init.d] 10-config: exited 0.
[cont-init.d] 20-config: executing...
Hello Jitsi
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by frispete** [comment] 2022-01-04 13:54
Thanks, @prayagsingh for testing. What steps did you conduct in point 3? After cleaning up everything, I'm using
```
docker-compose -f docker-compose.yml -f jigasi.yml -f jibri.yml -f etherpad.yml up -d
```
to build and run the containers.

**Comment by prayagsingh** [comment] 2022-01-04 14:09
@frispete In Step 3, I ran `docker image build -t image_name` inside `web` directory to create an image for web container.

**Comment by frispete** [comment] 2022-01-04 15:10
Thanks, will test later..

Last year, I built from a git checkout using make.

**Comment by prayagsingh** [comment] 2022-01-04 16:21
> Thanks, will test later..
> 
> Last year, I built from a git checkout using make.

Yes, when you run `Make` command, it will creates docker images for you. But it will create `jitsi/web:latest` then in order to use it on server(if jitsi is deployed on VM), you have to push it to docker hub.

**Comment by saghul** [comment] 2022-01-05 10:25
Closing since the problem is you never built the images, as @prayagsingh pointed out.

**Closed by saghul** 2022-01-05 10:25 UTC
