### ISSUE TITLE
Sessions with minus or underscore create 404

### ISSUE THREAD

**Issue by MaxNoe** [jitsi/docker-jitsi-meet#290] opened 2020-03-25 15:16 UTC
Session names containing hyphens or underscore just create a plain 404.

If this is indeed just not possible for some reason, validation for the form on the main page and a more help full error page for directly connecting would be helpful

**Comment by timonegk** [comment] 2020-03-25 15:28
This should have been fixed in #245.

**Comment by Craeckie** [comment] 2020-03-25 19:46
Same here. I tried with "sdf-sdf" and it seems to match the wrong rule:
`[error] 225#225: *4 open() "/usr/share/jitsi-meet/sdf-sdf" failed (2: No such file or directory), client: x.x.x.x, server: _, request: "GET /sdf-sdf HTTP/1.1", host: "x.x.x", referrer: "https://x.x.x/"`

Looks like it uses this rule:
```
location ~ ^/(libs|css|static|images|fonts|lang|sounds|connection_optimization|.well-known)/(.*)$
{
    add_header 'Access-Control-Allow-Origin' '*';
    alias /usr/share/jitsi-meet/$1/$2;
}
```
I don't know how that happened.

**Comment by saghul** [comment] 2020-03-25 20:24
Are you using the latest images?

**Closed** 2020-03-26 10:53 UTC

**Comment by MaxNoe** [comment] 2020-03-26 11:10
Could you make a new release to dockerhub?

**Comment by saghul** [comment] 2020-03-26 13:41
4101-2 is available now 🚀

**Comment by MaxNoe** [comment] 2020-03-26 13:42
awesome, thank you!

**Comment by MaxNoe** [comment] 2020-03-26 18:52
I just deployed it and it still gives 404 for urls containing hyphens or underscores

**Comment by saghul** [comment] 2020-03-26 20:43
Have you deleted your CONFIG volume?

**Comment by MaxNoe** [comment] 2020-03-26 21:15
Yes, two times.

**Comment by saghul** [comment] 2020-03-27 08:43
How does the generated nginx config file look like?

**Comment by MaxNoe** [comment] 2020-03-27 09:01
```
# cat meet.conf 
server_name _;

client_max_body_size 0;

root /usr/share/jitsi-meet;
index index.html
error_page 404 /static/404.html;

location ~ ^/([a-zA-Z0-9=\?]+)$ {
    rewrite ^/(.*)$ / break;
}

location /config.js {
    alias /config/config.js;
}

location /interface_config.js {
    alias /config/interface_config.js;
}

location /external_api.js {
    alias /usr/share/jitsi-meet/libs/external_api.min.js;
}

location / {
    ssi on;
}

# BOSH
location /http-bind {
    proxy_pass http://xmpp.meet.jitsi:5280/http-bind;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host meet.jitsi;
}```

**Comment by MaxNoe** [comment] 2020-03-27 09:05
Which indeed looks like the old one and not like the current master.
https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/meet.conf

Did I something wrong or did you deploy and old version to dockerhub?

**Comment by MaxNoe** [comment] 2020-03-27 13:26
Ok, seems to be an error on my end, with a fresh docker-compose start it worked.

**Comment by saghul** [comment] 2020-03-27 15:01
No worries!

**Comment by MaxNoe** [comment] 2020-03-28 10:44
Turns out the images running were still the old ones because I had not activated the "Always pull image before creating" in our Rancher for the jitsi services and there was a "latest" image present.

**Comment by sapkra** [comment] 2020-03-28 18:00
@MaxNoe I would recommend to always use images with version tags also to prevent breaking changes with newer images.

**Comment by MaxNoe** [comment] 2020-03-28 18:03
I did. For the upgrade anyways. It was really the "always pull on creation"

**Comment by flantel** [comment] 2020-03-31 14:23
@MaxNoe Care to share your rancher-config.yml and docker-config.yml?

Thanks

**Comment by christianhauff** [comment] 2020-04-21 12:19
Is there anything to do when upgrading from an older version except from:
* Pulling the Repo
* Removing all Containers
* Removing all Images
* Removing all Volumes
* Restarting with docker-compose

The issue is still present for me, anyone else got that problem?

**Comment by saghul** [comment] 2020-04-21 12:27
You need to update the images, run: `docker-compose pull` I'll update the docs shortly.

**Comment by christianhauff** [comment] 2020-04-21 12:36
still no difference with that...

```
web_1      | <ip> - - [21/Apr/2020:14:33:55 +0200] "HEAD /name-with-dash HTTP/1.1" 404 0 "-" "curl/7.69.1"
web_1      | 2020/04/21 14:33:55 [error] 225#225: *2 open() "/usr/share/jitsi-meet/name-with-dash" failed (2: No such file or directory), client: <ip>, server: _, request: "HEAD /name-with-dash HTTP/1.1", host: "localhost:8000"
```
I'm using ProxyPass of Apache to forward the HTTPS-Port, but that shouldn't make a difference I think.

**Comment by christianhauff** [comment] 2020-04-22 11:22
Just figured it out! I also had to delete and recreate the `~/.jitsi-meet-cfg`-Directory, now it's working!
