### ISSUE TITLE
SpeakerStats don't work anymore

### ISSUE THREAD

**Issue by JacBra** [jitsi/docker-jitsi-meet#774] opened 2020-10-08 19:28 UTC
I installed stable-5076 (from scratch). The speaker stats aren't working anymore.
Before I used stable-4857. I did a compare but couldn't find any difference that would relate to the speaker stats.
Has anyone else seen this same behaviour?

Moreover, conference duration only works when authentication is disabled (ENABLE_AUTH=0 in .env).
I'm not sure whether this is since stable-5076, or that this happened before.

**Comment by sysadmama** [comment] 2020-10-09 12:36
I tried to work with stable-5076, but I ran into so many problems that I just switched back to stable-4857.
Indeed, non-working speakerstats was one of my problems. So I can confirm what @JacBra wrote few hours ago.

**Comment by saghul** [comment] 2020-10-09 12:53
Thanks for the report, we'll take a look!

**Comment by saghul** [comment] 2020-10-09 12:53
@sysadmama Did you have any authentication configured?

**Comment by sysadmama** [comment] 2020-10-09 19:31
> @sysadmama Did you have any authentication configured?

Indeed @saghul `ENABLE_AUTH=1` with `AUTH_TYPE=internal` is set.

**Comment by MarkusPaul1989** [comment] 2020-10-15 11:53
After updating yester, I got the same issue.
The speaker stats are displayed, but the time counter always show zero seconds for all participants.
Is there any a solution or a work-around yet?

**Comment by JacBra** [comment] 2020-10-20 09:12
With stable-5142 the speaker stats work again. Thanks!
The conference duration does still not work.

**Comment by MarkusPaul1989** [comment] 2020-10-20 10:26
Hi @JacBra,
this might be a prosody configuration located in the jitsi-meet.cfg.lua file

**Comment by juradoz** [comment] 2020-10-20 19:54
Confirmed speakerstats not working on vanilla docker instalation, pulled from stable-5142.

**Comment by juradoz** [comment] 2020-10-20 21:21
Problem gets solved if ~/.jitsi-meet-cfg/web/config.js gets edited AFTER web container is started. Last occurrence of config.openBridgeChannel must be set to true:

config.openBridgeChannel = true;

Parameter gets reset to 'websocket' on every 'web' container restart or creation.

**Comment by juradoz** [comment] 2020-10-20 22:13
On top of not overriding ~/.jitsi-meet-cfg/web/config.js file (since it is monted on a volume so custom parameters can get persisted out of transient containers), web/rootfs/defaults/settings-config.js should somehow allow setting true (no quotes) to config.js.

**Comment by JacBra** [comment] 2020-10-26 16:08
> 
> 
> Hi @JacBra,
> this might be a prosody configuration located in the jitsi-meet.cfg.lua file

https://github.com/jitsi/docker-jitsi-meet/commit/bec928c3aa6c512fde98ad3d746963107c8f8e3c#diff-199f45103a3a23a514583143479a6ce9a61672842b115a183202503dbf315459

I think that this pull request has something to do with it, but I can't exactly know how the syntax of these .lua files/templates work. Can someone point me to a direction for that? Thanks a lot.

**Comment by debfx** [comment] 2020-11-03 17:16
Removing the configs in `web/nginx/` and restarting the container fixed the issue for me.

The websocket requires changes in nginx's `meet.conf`. They were done in `web/rootfs/defaults/meet.conf` but `web/rootfs/etc/cont-init.d/10-config` doesn't touch the config inside the container if already exists. As a result jvb websockets are broken on upgrade.

**Comment by JacBra** [comment] 2020-11-04 11:59
I found that the conference duration works fine when authentication is disabled. When (LDAP) authentication is enabled, it doesn't work anymore.

**Comment by prayagsingh** [comment] 2020-11-09 13:56
> 
> 
> Removing the configs in `web/nginx/` and restarting the container fixed the issue for me.
> 
> The websocket requires changes in nginx's `meet.conf`. They were done in `web/rootfs/defaults/meet.conf` but `web/rootfs/etc/cont-init.d/10-config` doesn't touch the config inside the container if already exists. As a result jvb websockets are broken on upgrade.

Can you please share which config did you remove?

**Comment by prayagsingh** [comment] 2020-11-09 14:01
@saghul I'm using master branch and still speaker-stats aren't coming up. Also, I'm getting `Failed to send E2E ping request or response. undefined` warning in console continuously. Getting both errors when using websocket.

**Comment by mfts** [comment] 2020-11-09 15:16
I'm seeing the same thing as @prayagsingh

**Comment by debfx** [comment] 2020-11-09 16:45
> Can you please share which config did you remove?

All *.conf files inside the web/nginx/ config subdirectory (as set in the `CONFIG` variable in `.env`).

**Comment by prayagsingh** [comment] 2020-11-21 17:34
**Update**
I have created jicofo/jvb unstable image and I'm not seeing Speaker stats and E2E errors any more. So,I think this issue will be fixed in next release.  
@saghul  @mfts

**Comment by netcom** [comment] 2020-12-07 08:21
Issue is in config variable in config.js, config variable `config.openBridgeChannel` has quotes in its value, but it should be set to boolean value.

How to check if this affects you?

Open in browser: https://yourjitsideployment.com/config.js
Check if config.openBridgeChannel = 'true'; // (this has quotes but it should be boolean)

**Comment by F-Node-Karlsruhe** [comment] 2021-01-11 22:18
> 
> 
> Issue is in config variable in config.js, config variable `config.openBridgeChannel` has quotes in its value, but it should be set to boolean value.
> 
> How to check if this affects you?
> 
> Open in browser: https://yourjitsideployment.com/config.js
> `Check if config.openBridgeChannel = 'true'; // (this has quotes but it should be boolean)`

The issue still persists in the latest version :/

**Comment by saghul** [comment] 2021-01-12 08:38
The default is "websocket", did you override the value?

**Comment by F-Node-Karlsruhe** [comment] 2021-01-12 09:19
Yes, went into the container, changed the value and restarted it. Checked on domain/config.js

**Comment by sysadmama** [comment] 2021-02-01 20:06
After upgrading to `5390-1` Docker environment, speaker stats were still broken; in Chrome Developer Tools, there were lots of errors I only saw when I entered the conference at least three times to avoid p2p. The errors were like this:
```
SEVERE: EndpointMessageTransport still not connected.
```
Which leads back to something's broken with the websockets. Last but not least I ended up adjusting `nginx` config so it looks like this now:
```
  location / {
    proxy_pass		http://127.0.0.1:8050;
    proxy_http_version  1.1;
    proxy_set_header    Upgrade $http_upgrade;
    proxy_set_header    Connection "upgrade";
    proxy_set_header	Host $host;

    proxy_set_header	X-Real-IP $remote_addr;
    proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header	X-Forwarded-Proto $proxy_x_forwarded_proto;

    tcp_nodelay on;
  }
```

After restarting `nginx` and re-joining the conference, the errors in Developer Tools Console are gone – and finally the speaker stats are doing again what I expect them to do ;) 

HTH,
  Marianne

**Comment by saghul** [comment] 2021-04-16 14:21
New stable release is out.

**Closed by saghul** 2021-04-16 14:21 UTC
