### ISSUE TITLE
How to update DOCKER_HOST_ADDRESS

### ISSUE THREAD

**Issue by wackazong** [jitsi/docker-jitsi-meet#539] opened 2020-05-02 11:55 UTC
How can we update DOCKER_HOST_ADDRESS if it changes while the server is running? E.g. if the LAN router restarts a DSL connection and gets assigned a new public IP address.

**Comment by saghul** [comment] 2020-05-02 14:41
The is no way do it automatically, sorry. The JVB does discover its own IP address using STUN so maybe try not setting it and it will hopefully work just fine.

**Comment by kescherCode** [comment] 2020-05-02 19:24
You might want to consider assigning your host a static IP address in your DHCP server (or home router). That way, it should stay the same.

**Comment by saghul** [comment] 2020-05-03 07:04
They probably are on a residential connection, so that won’t work...

**Comment by Echolon** [comment] 2020-06-19 20:50
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-06-19 20:50 UTC
Labels: question
