### ISSUE TITLE
Video Flickering on Screen Sharing from Chrome to Chrome

### ISSUE THREAD

**Issue by creativeguitar** [jitsi/docker-jitsi-meet#674] opened 2020-07-10 17:17 UTC
Screen sharing has a slight but annoying flickering when a user with chrome shares content to another user with Chrome
Chrome version: 83.0.4103.116

Issue only happens when 
Screen Sharing user "Chrome" - Other user "Chrome"

Issue is not present in the following scenarios:
Screen Sharing user "Chrome" - Other user "FireFox"
Screen Sharing user "FireFox" - Other user "FireFox"
Screen Sharing user "FireFox" - Other user "Chrome"

**Comment by Kirides** [comment] 2020-10-23 12:58
i can confirm this 
![wq9rBEQWPo](https://user-images.githubusercontent.com/13602143/97006448-30750e00-1540-11eb-9494-bf879332f18a.gif)

**Comment by tomiboy78** [comment] 2020-11-19 13:41
Its the Chrome/Chromium GPU Acceleration. If you start the Browser with --disable-gpu , the flickering disappear.

**Comment by saghul** [comment] 2020-11-19 15:15
Thanks for the heads up @tomiboy78 ! I'll close this since there is nothing we can do on our side.

**Closed by saghul** 2020-11-19 15:15 UTC
