### ISSUE TITLE
Cannot host meeting with internal authentication

### ISSUE THREAD

**Issue by RoderickVM** [jitsi/docker-jitsi-meet#1022] opened 2021-04-17 20:30 UTC
With the latest version (5765), every time I start a meeting as a host, the application shows an "Obtaining session-id..." message below the password field in the "Authentication required" dialog box. This happens in both the Android app and the website. I made sure the user is created correctly in prosody, as per the instructions.

Any help to solve this issue is greatly appreciated.

**Comment by saghul** [comment] 2021-04-17 20:57
Please search the open issues  before opening a new one. Duplicate of https://github.com/jitsi/docker-jitsi-meet/issues/1018

**Closed by saghul** 2021-04-17 20:57 UTC
