### ISSUE TITLE
Lobby not working with JWT on docker latest

### ISSUE THREAD

**Issue by Shotster** [jitsi/docker-jitsi-meet#838] opened 2020-11-23 18:38 UTC
I have JWT and guest access working with docker latest. However, if I set `ENABLE_LOBBY=1` in `.env`, there is no lobby option in the UI after clicking the shield icon. I do see the new E2E encryption experimental feature, but no lobby. Is there something besides setting the environment variable that must be done to get it to work?

**Comment by cameroncros** [comment] 2020-11-24 07:24
For what its worth, i had a similar issue (along with some others), which was fixed by purging my .jitsi-meet-config directory and recreating everything. Not sure if that is really a viable fix.

**Comment by saghul** [comment] 2020-11-24 08:50
Wipe your config volume and restart the container.

**Comment by Shotster** [comment] 2020-11-24 11:18
> Wipe your config volume and restart the container.

Of course, that was the first thing I tried. Just did that again, and no go. All I see are the password and E2E encryption options. Oh well, whatever.

**Comment by saghul** [comment] 2020-11-24 11:41
Hum, that's unexpected. What release did you install? Can you share your generated Prosody config file? (not the general one, the Jitsi specific one)

**Comment by cameroncros** [comment] 2020-11-24 11:46
I have to login as root, and delete `/root/.jitsi-meet-config` to properly reset the config. The one in my home directory was incorrect, because to execute the docker-compose command, I used sudo.

**Comment by Shotster** [comment] 2020-11-24 12:22
> What release did you install?

Latest master. I also deleted all containers so they'd be rebuilt. I have enabled lobby, guests, and JWT auth.

> Can you share your generated Prosody config file?

```
admins = {
    "focus@auth.meet.jitsi",
    "jvb@auth.meet.jitsi"
}

plugin_paths = { "/prosody-plugins/", "/prosody-plugins-custom" }
http_default_host = "meet.jitsi"














VirtualHost "meet.jitsi"

  
    authentication = "token"
    app_id = "my_jitsi_app_id"
    app_secret = "abc123DOREME"
    allow_empty_token = true
    

    

    ssl = {
        key = "/config/certs/meet.jitsi.key";
        certificate = "/config/certs/meet.jitsi.crt";
    }
    modules_enabled = {
        "bosh";
        "pubsub";
        "ping";
        "speakerstats";
        "conference_duration";
        
        
        
    }

    

    speakerstats_component = "speakerstats.meet.jitsi"
    conference_duration_component = "conferenceduration.meet.jitsi"

    c2s_require_encryption = false


VirtualHost "guest.meet.jitsi"
    authentication = "anonymous"
    c2s_require_encryption = false

    
    modules_enabled = {
        "muc_lobby_rooms";
    }

    main_muc = "muc.meet.jitsi"
    lobby_muc = "lobby.meet.jitsi"
    
    muc_lobby_whitelist = { "recorder.meet.jitsi" }
    
    



VirtualHost "auth.meet.jitsi"
    ssl = {
        key = "/config/certs/auth.meet.jitsi.key";
        certificate = "/config/certs/auth.meet.jitsi.crt";
    }
    authentication = "internal_hashed"


VirtualHost "recorder.meet.jitsi"
    modules_enabled = {
      "ping";
    }
    authentication = "internal_hashed"


Component "internal-muc.meet.jitsi" "muc"
    storage = "memory"
    modules_enabled = {
        "ping";
        
    }
    muc_room_locking = false
    muc_room_default_public_jids = true

Component "muc.meet.jitsi" "muc"
    storage = "memory"
    modules_enabled = {
        "muc_meeting_id";
        
        
        "token_verification";
        
    }
    muc_room_cache_size = 1000
    muc_room_locking = false
    muc_room_default_public_jids = true

Component "focus.meet.jitsi"
    component_secret = "7960b59ee8a1d40c0be645cd7097363c"

Component "speakerstats.meet.jitsi" "speakerstats_component"
    muc_component = "muc.meet.jitsi"

Component "conferenceduration.meet.jitsi" "conference_duration_component"
    muc_component = "muc.meet.jitsi"


Component "lobby.meet.jitsi" "muc"
    storage = "memory"
    restrict_room_creation = true
    muc_room_locking = false
    muc_room_default_public_jids = true
```

**Comment by saghul** [comment] 2020-11-24 13:09
Your config looks good. I'll try to reproduce the problem. Do you see any logs in the Prosody container or the JS console regarding the lobby?

**Comment by Shotster** [comment] 2020-11-24 15:24
> Do you see any logs in the Prosody container or the JS console regarding the lobby?

No errors (or even messages) in the browser console referencing "lobby".

Here's the output during prosody container start-up...

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
Adding user `prosody' to group `sasl' ...
Adding user prosody to group sasl
Done.
mv: cannot stat '/config/data/*.crt': No such file or directory
mv: cannot stat '/config/data/*.key': No such file or directory
[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
saslauthd[228] :num_procs  : 5
saslauthd[228] :mech_option: /etc/saslauthd.conf
saslauthd[228] :run_path   : /var/run/saslauthd
saslauthd[228] :auth_mech  : ldap
saslauthd[228] :mmaped shared memory segment on file: /var/run/saslauthd/cache.mmap
saslauthd[228] :bucket size: 96 bytes
saslauthd[228] :stats size : 36 bytes
saslauthd[228] :timeout    : 28800 seconds
saslauthd[228] :cache table: 985828 total bytes
saslauthd[228] :cache table: 1711 slots
saslauthd[228] :cache table: 10266 buckets
saslauthd[228] :flock file opened at /var/run/saslauthd/cache.flock
saslauthd[228] :using accept lock file: /var/run/saslauthd/mux.accept
saslauthd[228] :master pid is: 0
saslauthd[228] :listening on socket: /var/run/saslauthd/mux
saslauthd[228] :using process model
saslauthd[228] :forked child: 241
saslauthd[228] :forked child: 242
saslauthd[241] :acquired accept lock
saslauthd[228] :forked child: 243
saslauthd[228] :forked child: 244
startup             info	Hello and welcome to Prosody version 0.11.5
startup             info	Prosody is using the epoll backend for connection handling
portmanager         info	Activated service 'c2s' on [*]:5222, [::]:5222
portmanager         info	Activated service 'legacy_ssl' on no ports
general             info	Starting conference duration timer for muc.meet.jitsi
conferenceduration.meet.jitsi:conference_duration_component  info	No muc component found, will listen for it: muc.meet.jitsi
muc.meet.jitsi:token_verification                            warn	WARNING - empty tokens allowed
conferenceduration.meet.jitsi:conference_duration_component  info	Hook to muc events on muc.meet.jitsi
portmanager                                                  info	Activated service 'component' on [*]:5347
meet.jitsi:auth_token                                        warn	WARNING - empty tokens allowed
portmanager                                                  info	Activated service 'http' on [*]:5280, [::]:5280
portmanager                                                  info	Activated service 'https' on no ports
guest.meet.jitsi:muc_lobby_rooms                             info	Lobby component loaded lobby.meet.jitsi
general                                                      info	Starting speakerstats for muc.meet.jitsi
speakerstats.meet.jitsi:speakerstats_component               info	Hook to muc events on muc.meet.jitsi
c2s556113e77820                                              info	Client connected
c2s5561148795f0                                              info	Client connected
c2s556113e77820                                              info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
c2s556113e77820                                              info	Authenticated as jvb@auth.meet.jitsi
c2s5561148795f0                                              info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
c2s5561148795f0                                              info	Authenticated as focus@auth.meet.jitsi
focus.meet.jitsi:component                                   warn	Component not connected, bouncing error for: <iq from='focus@auth.meet.jitsi/focus600865600297133' to='focus.meet.jitsi' type='get' id='8qlVB-44'>
jcp556113f667d0                                              info	Incoming Jabber component connection
focus.meet.jitsi:component                                   info	External component successfully authenticated
mod_bosh                                                     info	New BOSH session, assigned it sid 'effd85ce-d001-4b01-b1f3-d0fc3383bf54'
bosheffd85ce-d001-4b01-b1f3-d0fc3383bf54                     info	Authenticated as c355cd1c-e7c5-40e1-aef2-8556590e9eb6@meet.jitsi
speakerstats.meet.jitsi:speakerstats_component               warn	A module has been configured that triggers external events.
speakerstats.meet.jitsi:speakerstats_component               warn	Implement this lib to trigger external events.
bosheffd85ce-d001-4b01-b1f3-d0fc3383bf54                     info	BOSH client disconnected: session close
mod_bosh                                                     info	New BOSH session, assigned it sid '1922af41-3026-47ca-b134-7315dca350ae'
bosh1922af41-3026-47ca-b134-7315dca350ae                     info	Authenticated as 24b72426-6298-43c1-bec8-3bb513091b97@meet.jitsi
speakerstats.meet.jitsi:speakerstats_component               warn	A module has been configured that triggers external events.
speakerstats.meet.jitsi:speakerstats_component               warn	Implement this lib to trigger external events.
bosh1922af41-3026-47ca-b134-7315dca350ae                     info	BOSH client disconnected: session close
mod_bosh                                                     info	New BOSH session, assigned it sid 'f032606f-58d9-46d5-bb0e-1f54caf4ea35'
boshf032606f-58d9-46d5-bb0e-1f54caf4ea35                     info	Authenticated as edcb9f9b-9a7c-450d-94d3-bea8f360c874@guest.meet.jitsi
```

**Comment by Shotster** [comment] 2020-11-25 23:36
I had time to do a little client-side debugging, and it seems the issue is related to the fact that [this method](https://github.com/jitsi/lib-jitsi-meet/blob/33307629947bf32055f2cbc1798add0871c9ec1e/modules/xmpp/Lobby.js#L52-L54) is returning _undefined_, and therefore, the lobby is disabled even though the module loaded just fine.

I don't know enough about Jitsi's internal workings to understand why. Does anyone have any ideas?

**Comment by saghul** [comment] 2020-11-26 08:27
Any chance you can give #840 a try? Note you'll need to run `make` to build your own images.

**Comment by Shotster** [comment] 2020-11-26 20:38
> Any chance you can give #840 a try? Note you'll need to run `make` to build your own images.

Didn't make a difference, unfortunately.

I don't know jack cheese about React, but I did notice that there's a `state` object, and the `state['features/lobby'].lobbyEnabled` [property](https://github.com/jitsi/jitsi-meet/blob/baa39896f134f974ba35995fac2066a7886f2ff5/react/features/lobby/components/web/LobbySection.js#L138) is false (which is a lie because the lobby is definitely enabled in my `.env` file)...

![lobby-enabled](https://user-images.githubusercontent.com/628870/100390002-40bf5380-2fec-11eb-9467-c01e54707bff.png)

**Comment by saghul** [comment] 2020-11-27 11:36
I think it might be due to: https://github.com/jitsi/jitsi-meet/issues/8173

**Comment by Shotster** [comment] 2020-11-27 13:18
> I think it might be due to: [jitsi/jitsi-meet#8173](https://github.com/jitsi/jitsi-meet/issues/8173)

That issue describes what happens when a user requests entry to a room. My issue is that I don’t even get the UI to enable the lobby to begin with. As I’ve already shown in the screenshot above, I don’t see the lobby option after clicking the shield icon.

**Comment by saghul** [comment] 2020-11-27 14:45
I tried to repro with the Buster branch (#840) but I do see the lobby option. This was without auth though. That's why I think it might be related.

**Comment by Shotster** [comment] 2020-11-28 19:59
> I tried to repro with the Buster branch (#840) but I do see the lobby option. This was without auth though. That's why I think it might be related.

I think you may be right. If I disable guests, then I get the lobby option. Hopefully, [the PR](https://github.com/jitsi/jitsi-meet/pull/8174/files) does the trick. I'm not sure how to incorporate that change into the docker version of Jitsi, so I guess I'll just wait for the docker repo to be updated.

**Comment by DominikTrenz** [comment] 2020-12-08 09:15
I got the same problem and did some testing - maybe it helps. If i edit those two lines and remove (not $ENABLE_GUEST_DOMAIN) it seems to work (the lobby feature appears in moderator and guest view). 

https://github.com/jitsi/docker-jitsi-meet/blob/465816b4ebf2babf1b9e6daf007301c1fd17552e/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L79


https://github.com/jitsi/docker-jitsi-meet/blob/465816b4ebf2babf1b9e6daf007301c1fd17552e/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L90

There seems to be another problem if i change the two lines mentioned. The lobby host doesn't receive the request to accept the participant with following error message:

`prosody_1  | stanzarouter                                                 warn  Received stanza with invalid destination JID: angrywhalesgrowhigh@lobby.meet.jitsiangrywhalesgrowhigh@lobby.meet.jitsi/a4294c9f
`

**Comment by DominikTrenz** [comment] 2020-12-08 11:09
Ok, moving all the lobby configuration from the guest domain to the main domain worked. Now all lobby features and jwt authentication are working. The error above disappeared after deleting the lines in the guest domain

**Comment by Shotster** [comment] 2020-12-08 14:02
> Ok, moving all the lobby configuration from the guest domain to the main domain worked.

Yeah, I think that's what [this fix](https://github.com/jitsi/lib-jitsi-meet/commit/968f9476271c944f219c6fb9cf7f52b487963cf0) does. I haven't tried it in docker yet though.

**Comment by prayagsingh** [comment] 2020-12-08 14:13
> 
> 
> Ok, moving all the lobby configuration from the guest domain to the main domain worked. Now all lobby features and jwt authentication are working. The error above disappeared after deleting the lines in the guest domain

Can you please share your entire `jitsi-meet.cfg.lua` file?

**Comment by DominikTrenz** [comment] 2020-12-08 18:14
> > Ok, moving all the lobby configuration from the guest domain to the main domain worked. Now all lobby features and jwt authentication are working. The error above disappeared after deleting the lines in the guest domain
> 
> Can you please share your complete `jitsi-meet.cfg.lua` file?

Sure. I opened a pull request. I'm really not sure if the configuration is correct but it works with jwt auth + lobby + guest login activated.

**Comment by Shotster** [comment] 2020-12-08 18:57
> it works with jwt auth + lobby + guest login activated.

Confirmed! Thanks much!

**Comment by prayagsingh** [comment] 2020-12-09 04:07
> > > Ok, moving all the lobby configuration from the guest domain to the main domain worked. Now all lobby features and jwt authentication are working. The error above disappeared after deleting the lines in the guest domain
> > 
> > Can you please share your complete `jitsi-meet.cfg.lua` file?
> 
> Sure. I opened a pull request. I'm really not sure if the configuration is correct but it works with jwt auth + lobby + guest login activated.

I have added my comment in the pull request. Did you test the recording with this new config? I'm sure recording won't work with lobby without whitelisting jibri domain.

**Comment by DominikTrenz** [comment] 2020-12-09 07:33
> > > > Ok, moving all the lobby configuration from the guest domain to the main domain worked. Now all lobby features and jwt authentication are working. The error above disappeared after deleting the lines in the guest domain
> > > 
> > > 
> > > Can you please share your complete `jitsi-meet.cfg.lua` file?
> > 
> > 
> > Sure. I opened a pull request. I'm really not sure if the configuration is correct but it works with jwt auth + lobby + guest login activated.
> 
> I have added my comment in the pull request. Did you test the recording with this new config? I'm sure recording won't work with lobby without whitelisting jibri domain.

I didn't test it but the whitelisting config should be included:
```
{{ if .Env.XMPP_RECORDER_DOMAIN }}
    muc_lobby_whitelist = { "{{ .Env.XMPP_RECORDER_DOMAIN }}" }
{{ end }}
```

**Comment by hiteshsaini33** [comment] 2020-12-11 18:35
> I have JWT and guest access working with docker latest. However, if I set `ENABLE_LOBBY=1` in `.env`, there is no lobby option in the UI after clicking the shield icon. I do see the new E2E encryption experimental feature, but no lobby. Is there something besides setting the environment variable that must be done to get it to work?

I am finding problem in jwt configuring. Can you tell me how can i do this.

**Comment by hiteshsaini33** [comment] 2020-12-11 18:39
> > > > > Ok, moving all the lobby configuration from the guest domain to the main domain worked. Now all lobby features and jwt authentication are working. The error above disappeared after deleting the lines in the guest domain
> > > > 
> > > > 
> > > > Can you please share your complete `jitsi-meet.cfg.lua` file?
> > > 
> > > 
> > > Sure. I opened a pull request. I'm really not sure if the configuration is correct but it works with jwt auth + lobby + guest login activated.
> > 
> > 
> > I have added my comment in the pull request. Did you test the recording with this new config? I'm sure recording won't work with lobby without whitelisting jibri domain.
> 
> I didn't test it but the whitelisting config should be included:
> 
> ```
> {{ if .Env.XMPP_RECORDER_DOMAIN }}
>     muc_lobby_whitelist = { "{{ .Env.XMPP_RECORDER_DOMAIN }}" }
> {{ end }}
> ```

I have a jitsi server with docker. I am finding problem to configure jwt in jitsi. Can you tell me how to configure? I have done everything according to jitsi docker official documentation.

**Comment by DominikTrenz** [comment] 2020-12-22 10:07
> > > > > > Ok, moving all the lobby configuration from the guest domain to the main domain worked. Now all lobby features and jwt authentication are working. The error above disappeared after deleting the lines in the guest domain
> > > > > 
> > > > > 
> > > > > Can you please share your complete `jitsi-meet.cfg.lua` file?
> > > > 
> > > > 
> > > > Sure. I opened a pull request. I'm really not sure if the configuration is correct but it works with jwt auth + lobby + guest login activated.
> > > 
> > > 
> > > I have added my comment in the pull request. Did you test the recording with this new config? I'm sure recording won't work with lobby without whitelisting jibri domain.
> > 
> > 
> > I didn't test it but the whitelisting config should be included:
> > ```
> > {{ if .Env.XMPP_RECORDER_DOMAIN }}
> >     muc_lobby_whitelist = { "{{ .Env.XMPP_RECORDER_DOMAIN }}" }
> > {{ end }}
> > ```
> 
> I have a jitsi server with docker. I am finding problem to configure jwt in jitsi. Can you tell me how to configure? I have done everything according to jitsi docker official documentation.

You need to build the docker image yourself with the fix i provided or wait for someone to merge my pull request.

**Comment by saghul** [comment] 2021-02-02 09:13
This should be fixed as of stable-5390-2.

**Closed by saghul** 2021-02-02 09:13 UTC
