### ISSUE TITLE
Authentication with JWT just doesn't work

### ISSUE THREAD

**Issue by serban-mihai** [jitsi/docker-jitsi-meet#83] opened 2019-03-21 09:58 UTC
From dev branch:
I tried to make jitsi to autenticate with JWT but it just doesn't wanna work.
Now I started to think that maybe is my token structure that is broken since there are no relevant info in any log and the parameter passed with ?jwt= in the URL are recognized correctly from the browser that just gives always back an error about connection.passwordRequired but I suspect that is referred to the room pass that is never present.

Logs from docker-compose when authenticating with JWT:
![Screenshot_2019-03-21_11-49-44](https://user-images.githubusercontent.com/34487580/54744542-ec858e80-4bcf-11e9-90f8-fb1c0358a850.png)

This is what I get every time I try to get into any room with a token:
![Screenshot_2019-03-21_11-28-29](https://user-images.githubusercontent.com/34487580/54743478-e6da7980-4bcc-11e9-975d-044d7d803ae1.png)

And this is the Token structure I use:
![Screenshot_2019-03-21_11-20-00](https://user-images.githubusercontent.com/34487580/54743600-3e78e500-4bcd-11e9-8e15-8ff92f8a86f0.png)

As you can see (as today's date) the token isn't expired either so I don't think that's the problem.
Since I didn't set issuers and audience I put the ENV variable's JWT_APP_ID value in both "aud" and "iss" fields while I put the XMPP_DOMAIN in "sub" and let the "room" to "*".
There is also the JWT_APP_SECRET value in the signature.

At first I need to create at least one user in prosody's running container who will become administrator after creating a room but when I try to join the same room through JWT the result is the same as above.

ENABLE_AUTH and JWT_ENABLE_TOKEN_AUTH are both set to 1.
The result is the same also if I set ENABLE_GUESTS to 1 or not...

Chrome's Debugger sends me to this line of the JitsiConnection function that suggests me that the script doesn't get the appID but I'm not sure about this
![Screenshot_2019-03-21_11-48-03](https://user-images.githubusercontent.com/34487580/54744714-5b62e780-4bd0-11e9-996d-0775247dcd00.png)

Does someone have an idea about what I'm getting wrong?
I've been stuck with this problem for about a week and I'm running out of ideas

**Comment by saghul** [comment] 2019-03-21 10:03
How does your `.env` file (the JWT relevant options, that is) look like?

**Comment by serban-mihai** [comment] 2019-03-21 10:09
Thanks for replying so fast!

CONFIG=~/.jitsi-meet-cfg
ENABLE_AUTH=1
# ENABLE_GUESTS=1
JWT_ENABLE_TOKEN_AUTH=1
JWT_APP_ID=my_jitsi_app_id
JWT_APP_SECRET=some_secret
#JWT_ACCEPTED_ISSUERS=my_web_client,my_app_client
#JWT_ACCEPTED_AUDIENCES=my_server1,my_server2
XMPP_DOMAIN=meet.jitsi

All the other variables are as I got them by default from the repository

**Comment by damencho** [comment] 2019-03-21 10:10
Hey you are accessing http resource, this will not work with webrtc, you need https.

**Comment by serban-mihai** [comment] 2019-03-21 10:12
> Hey you are accessing http resource, this will not work with webrtc, you need https.

Even with HTTPS the results are the same, now isn't enabled cause I surpassed the limit for LetsEncrypt renewal

**Comment by serban-mihai** [comment] 2019-03-21 16:38
After spending a couple of hours on the Js Debugger I noticed that, at runtime, the appID field (which I think should be "my_jitsi_app_id" as specified in the .env) is always null. Not sure why or if that's how it's supposed to be but could anyone give me some feedback?

![Screenshot_2019-03-21_17-02-56](https://user-images.githubusercontent.com/34487580/54768645-42762880-4c08-11e9-8726-e8f6e42563d7.png)

**Comment by saghul** [comment] 2019-03-22 08:29
Did you change the value in the env file at some point after the containers were first started?

**Comment by serban-mihai** [comment] 2019-03-22 08:34
> Did you change the value in the env file at some point after the containers were first started?

Nope, I never touched anything in the root folder after starting the containtes, I also always removed the CONFIG folder and also stopped the containers with `docker-compose down --rmi all` to make sure that there are no possible error trace that could be left behind before another run

**Comment by saghul** [comment] 2019-03-23 07:26
Ok, you seem to be doing everything right. I'll take a look and see if I can reproduce it.

**Comment by serban-mihai** [comment] 2019-04-16 11:59
Any update about JWT Auth?
Besides the fact that the backend doesn't send many info such as appID correctly it also seems to fail because of "passwordRequired" for JID.
Even by injecting these info manually through the debugger at runtime it still breaks somewhere...

**Comment by saghul** [comment] 2019-04-17 07:40
Hi, sorry for the delay. I just tested the dev branch and it worked just fine with the following test JWT:

```
{
  "context": {
    "user": {
      "avatar": "https:/gravatar.com/avatar/abc123",
      "name": "John Doe",
      "email": "jdoe@example.com"
    }
  },
  "aud": "my_jitsi_app_id",
  "iss": "my_jitsi_app_id",
  "sub": "meet.jitsi",
  "room": "*"
}
```

Have you deleted the config directory every time you have changed the `.env` file? Also, check the prosody logs when JWT auth fails, they usually contain the reason.

**Comment by serban-mihai** [comment] 2019-04-17 08:19
> Hi, sorry for the delay. I just tested the dev branch and it worked just fine with the following test JWT:
> 
> ```
> {
>   "context": {
>     "user": {
>       "avatar": "https:/gravatar.com/avatar/abc123",
>       "name": "John Doe",
>       "email": "jdoe@example.com"
>     }
>   },
>   "aud": "my_jitsi_app_id",
>   "iss": "my_jitsi_app_id",
>   "sub": "meet.jitsi",
>   "room": "*"
> }
> ```
> 
> Have you deleted the config directory every time you have changed the `.env` file? Also, check the prosody logs when JWT auth fails, they usually contain the reason.

Thanks for the feedback, I'll try as soon as I can and I'll let you know!

**Comment by saghul** [comment] 2019-04-23 07:34
I'm going to close this since I verified it does work. Please reopen if you run into other issues.

**Closed by saghul** 2019-04-23 07:34 UTC
