### ISSUE TITLE
ServiceWorker won't activate since it's served with text/html mime type

### ISSUE THREAD

**Issue by ArtPixWebdesign** [jitsi/docker-jitsi-meet#831] opened 2020-11-21 10:09 UTC
Using the latest docker image to test the app, everything works fine on the mobile app (iPhone & android),
but in a browser (FF & Brave on Ubuntu) the "pwa-worker.js" is served as "text/html" mime type,
causing the browser to register it infinitely (at every auto-refresh), but never activates...
Didn't find any existing similar issue in the list.
Am I the only one ?  

Thanks

**Comment by ArtPixWebdesign** [comment] 2020-11-24 12:58
update : I tryed to reset the config dir, pull the images again, and the mime type didn't change, but now, it's working on browsers only (desktop & mobile) : the app doesn't connect anymore...

**Comment by raufaser** [comment] 2020-11-29 23:49
Any progress here?

**Comment by eleith** [comment] 2020-12-03 04:07
i can confirm this issue with the `latest` tag of jitsi/web.

i was able to instead update `docker-compose.yml` with the previous version from two months ago as follows:

```
web:                                                                                                 
     image: jitsi/web:stable-5142
```

and i'm able to load up jitsi rooms in a browser.

**Comment by saghul** [comment] 2020-12-03 08:12
This will be fixed in the next release, once we tag a new stable Jitsi Meet. It shouldn't, however, have any effect, at least I cannot reproduce that.

**Comment by ArtPixWebdesign** [comment] 2020-12-07 23:07
I pulled the images again, and nothing is working now, I'm stucked in the redirect loop... "You've been disconnected..."

**Comment by Bruce-Ming** [comment] 2020-12-13 05:20
> 我再次拉出图像，现在什么也没用，我陷入了重定向循环中……“您已断开连接……”

Yes i have the same problem。

**Comment by guano** [comment] 2021-01-17 04:30
Has there been any status update to this error? I have identical symptoms- works in mobile apps, but not through web browsers. I also see the error where pwa_worker.js has an incorrect mime type. Unfortunately when I try to downgrade to a different version, it returns a "bad gateway error". I suspect this is an interaction with traefik that I'm running.

**Comment by Thumpermat** [comment] 2021-01-18 10:59
I also updated the repository with `git pull`, used the new `env.example` as template and modified it accordingly, removed and re-created the config directory structure and it is still not working on browsers (I use Brave, which is Chromium based).

If I modify my `docker-compose.yml`file and change the web image to `image: jitsi/web:stable-5142` then it works again.

As I use the reverse proxy app on my Synology, I cannot do the changes suggested for nginx or apache.

**Comment by TheSleepySlee** [comment] 2021-01-22 20:27
Thanks @Thumpermat. Was facing same issue, this solved it. Also using reverse proxy on Synology.

**Comment by saghul** [comment] 2021-04-16 14:19
The bogus mime type is now fixed in the latest release.

**Closed by saghul** 2021-04-16 14:19 UTC

**Comment by TheSleepySlee** [comment] 2021-04-16 19:20
Doesn't seem to be fixed for me.

**Comment by saghul** [comment] 2021-04-16 20:50
See this regarding reverse proxies and workarounds: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-a-reverse-proxy

**Comment by TheSleepySlee** [comment] 2021-04-16 21:18
indeed, fixed my issue, thanks.
