### ISSUE TITLE
Bridge channel send: no opened channel

### ISSUE THREAD

**Issue by adlergfx** [jitsi/docker-jitsi-meet#263] opened 2020-03-22 20:28 UTC
I know that this issue happend more than once but maybe i found something different. I have a server using apache2 and installed jitsi as docker parallel. As far as i see the should not influence each other. Everything worked fine but if i connect to parties video and audio is not transfered. Before i got the error message in the subject i get:

[JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: TypeError: t[2] is undefined Script: https://www.cg-effects.de:8443/libs/lib-jitsi-meet.min.js?v=3577 Line: 6 Column: 253228 StackTrace:  TypeError: "t[2] is undefined"
    parseCandidate sdp.js:65
    RTCIceCandidate common_shim.js:85
    shimRTCIceCandidate common_shim.js:106
    o common_shim.js:27
Logger.js:125:17

First i thought that i got the typical error in jvb regading NAT_HARVESTER_PUBLIC_ADDRESS but this did not help. I can send additional logs, but is it possible that in my case i have a front-end bug because of the presented error?

**Comment by saghul** [comment] 2020-03-23 19:34
Looks like a problem parsing the SDP. What browser and version are you using? Can you send the full JS console logs? I believe we log each ICE candidate.

**Comment by sapkra** [comment] 2020-03-23 19:49
I recently added sentry to my deployment and was also able to find both errors.

### t[2] is undefined
`t[2] is undefined` is occurring on Firefox 74 on Windows and Firefox Mobile 76 on Android

Sentry is showing the following line:
```javascript
{snip} e.substring(10).split(" "))[0],component:parseInt(t[1],10),protocol:t[2].toLowerCase(),priority:parseInt(t[3],10),ip:t[4],port:parseInt(t[5] {snip}
```

So it should be this line in lib-jitsi-meet.
https://github.com/jitsi/lib-jitsi-meet/blob/44d2c7ba21af56834034438c68977a5e6af7c317/modules/xmpp/SDPUtil.js#L162

### Bridge channel send: no opened channel
This error seems to occur in the same Firefox version like the issue before but I've also found it on Electron 8.1.1.
```console
[modules/RTC/BridgeChannel.js] <e.value>:  Bridge Channel send: no opened channel.
```

**Comment by saghul** [comment] 2020-03-23 20:31
Hey @sapkra thanks for the insight! If tomorrow it not too hectic I'll reach out. What would the best way to reach you? Twitter DM?

**Comment by sapkra** [comment] 2020-03-23 20:32
Twitter DM is fine for me.

**Comment by adlergfx** [comment] 2020-03-23 21:02
I can also help or send additional logs if required. Sorry, but currently mixed between childs and home office. I am "happy" that i was not so wrong. I searched the error a longer time between videobridge and prosody as i saw that error

**Comment by sapkra** [comment] 2020-03-23 21:06
I thinks this would be helpful because I currently don't have server logs for these errors.

**Comment by graffen** [comment] 2020-03-24 15:42
I get this error as well, and also don't have functioning audio or video on calls. Anything I can provide to help?

**Comment by saghul** [comment] 2020-03-24 15:43
@graffen Are you ussing. Firefox 74?

**Comment by graffen** [comment] 2020-03-24 15:47
@saghul Yes

**Comment by graffen** [comment] 2020-03-24 15:49
Just tested in Chromium, that seems to work fine.

**Comment by saghul** [comment] 2020-03-24 15:57
This seems to confirm the suspicion that it's a change in FF 74. We have fixed it since, inadvertently though. It will be fixed when we update Jitsi Meet in the containers. We are working on it now, trying to iron out some last bugs.

**Comment by adlergfx** [comment] 2020-03-24 17:53
Jepp, tested Chromium too and works as expected. 
I was using Firefox Developer 75.0b7 so it may be an error since 74. Please give some feedback if you could identify the bug because it would be great to understand what has changed (again). I have always trouble with bugs like that.

**Comment by saghul** [comment] 2020-03-24 21:48
From what we know it seems to be the ICE candidate end event. It's somehow different and the parser in adapter.js fails.

**Comment by graffen** [comment] 2020-03-25 07:01
I just tested a bit more. In p2p mode it works between Chromium and my phone. If I switch off p2p mode (or join a third participant), video stops. I still see the same error in the browser console. Nothing interesting in the jvb logs.

**Comment by ACXVO42** [comment] 2020-03-25 12:23
Hey,
I am experiencing the same problem as described in the initial post, albeit it only happens occasionally (most frequently when there are more than two clients in the session). Once a session is "broken" the only way to fix the issue is to create a new session from scratch.

We are using Firefox 68.8.0esr so I have the feeling that this is no new problem since FF74 or FF75. Joining the session using Chrome on the same machine works fine.

Note: I am running jitsi-meet using the apt package, not the dockerized version.

I'd appreciate any advice/hints regarding this problem.

**Comment by saghul** [comment] 2020-03-25 14:24
The Dockerized version uses the Debian packages. You are on the same boat. Can you see if you can reproducce it on meet.jit.si ?

We are ironing out 1-2 last bugs before we update the stable packages.

**Comment by ACXVO42** [comment] 2020-03-25 15:22
Thank you for your reply! I just reproduced the error at meet.jit.si after some testing.
Attached the errors as well as the full console log.
[jitsi_error.log](https://github.com/jitsi/docker-jitsi-meet/files/4381746/jitsi_error.log)
[jitsi_full.log](https://github.com/jitsi/docker-jitsi-meet/files/4381747/jitsi_full.log)

**Comment by saghul** [comment] 2020-03-26 09:02
Thanks @ACXVO42

**Comment by saghul** [comment] 2020-03-26 09:08
Ah I think the fix is part of the Firefox work, right @jallamsetty1 ? (this is not on meet.jit.si)

**Comment by sapkra** [comment] 2020-03-27 00:33
I was looking for server errors which are happening with this bug and found this one:

```bash
JVB 2020-03-27 01:22:14.039 SEVERE: [4935] org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.log() Failed to accept a connection from a DTLS client!
java.io.IOException: org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl is closed!
  | at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.assertNotClosed(DatagramTransportImpl.java:124)
  | at org.jitsi.impl.neomedia.transform.dtls.DatagramTransportImpl.send(DatagramTransportImpl.java:477)
  | at org.bouncycastle.crypto.tls.DTLSRecordLayer.sendRecord(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSRecordLayer.send(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSReliableHandshake$RecordLayerBuffer.sendToRecordLayer(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeHandshakeFragment(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSReliableHandshake.writeMessage(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSReliableHandshake.resendOutboundFlight(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSReliableHandshake.receiveMessage(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSServerProtocol.serverHandshake(Unknown Source)
  | at org.bouncycastle.crypto.tls.DTLSServerProtocol.accept(Unknown Source)
  | at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.runInConnectThread(DtlsPacketTransformer.java:1043)
  | at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.access$000(DtlsPacketTransformer.java:40)
  | at org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer$1.run(DtlsPacketTransformer.java:1272)


```

**Comment by graffen** [comment] 2020-04-01 07:18
Any news on the update that fixes this issue?

**Comment by saghul** [comment] 2020-04-16 14:21
Should be fixed on the images release yesterdday. can you please update and report back?

**Comment by ACXVO42** [comment] 2020-04-16 15:36
Hey,

thank you for the big update yesterday. The situation using Firefox has definitely improved a lot. We just tested for ~20 minutes, three way video without any issues.

When testing with some more joining & leaving however, I noticed some odd behavior. I had two clients sending video (one webcam, one screensharing). When client 3 reloads the page,
 only the webcam videostream shows up, the shared screen is missing.

Attached the log from client 3 when it joins the room and fails to received the shared screen. Maybe you can get some info from it. :)

Receiver: FF 68.7.0esr
Screensharing-Sender: FF 68.6.0esr

[ff_console_log.log](https://github.com/jitsi/docker-jitsi-meet/files/4488240/ff_console_log.log)

**Comment by jallamsetty1** [comment] 2020-04-16 17:25
Hey there, thank you for the report and the logs. I will take a look and get back to you.

**Comment by jallamsetty1** [comment] 2020-04-16 17:57
@ACXVO42 The logs indicate that client 3 didn't receive the msid for the screen share source. What Jicofo version are you running ? We had this bug in Jicofo sometime back where it wouldn't send the correct source information to new participants who join the call after someone started a screensharing session. It has been fixed since then and this shouldn't happen anymore.

**Comment by ACXVO42** [comment] 2020-04-17 08:36
Hey @jallamsetty1 
thanks for the swift reply! Just checked, I am running jicofo 1.0-554-1, apt does not list any available updates. I upgraded the server to jitsi-meet 2.0.x a few days ago.

Attached please find the jicofo logfile from the time period teh above mentioned conference was happening. Compared to the FF log, everything is shifted by two hours, but besides that the timestmaps should be identical. 
Thank you for the help, I really appreciate it!

[jicofo.log](https://github.com/jitsi/docker-jitsi-meet/files/4491824/jicofo.log)

**Comment by jallamsetty1** [comment] 2020-04-17 19:31
I am confused by the Jicofo version you reported, the version running on meet.jit.si is 1.0.548. 
We just pushed the version running on meet to stable, please get the latest package and see if the issue is still reproducible.

**Comment by ACXVO42** [comment] 2020-04-27 12:34
Thanks for the reply. I just updated my package lists and I have jicofo 1.0-549-1 available. Will upgrade it as soon as possible and report back with results.

**Comment by saghul** [comment] 2020-10-02 15:41
Closing since after https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5076 channels now use WebSocket, this should make them more robust.

**Closed by saghul** 2020-10-02 15:41 UTC
