### ISSUE TITLE
how to setup a Jitsi server with Rancher and Traefik?

### ISSUE THREAD

**Issue by oprogramador** [jitsi/docker-jitsi-meet#457] opened 2020-04-15 11:25 UTC
With the following `docker-compose.yml` used in Rancher:
```
version: '2'

services:
    # Frontend
    web:
        image: jitsi/web
        ports:
            - '8000'
            - '8443'
        volumes:
            - /home/docker/.jitsi-meet-cfg/web:/config
            - /home/docker/.jitsi-meet-cfg/web/letsencrypt:/etc/letsencrypt
            - /home/docker/.jitsi-meet-cfg/transcripts:/usr/share/jitsi-meet/transcripts
        environment:
            - JICOFO_AUTH_USER=focus
            - XMPP_DOMAIN=meet.jitsi
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
            - XMPP_GUEST_DOMAIN=guest.meet.jitsi
            - XMPP_MUC_DOMAIN=muc.meet.jitsi
            - XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
            - TZ=Europe/Amsterdam
            - JIBRI_BREWERY_MUC=jibribrewery
            - JIBRI_PENDING_TIMEOUT=90
            - JIBRI_XMPP_USER=jibri
            - JIBRI_XMPP_PASSWORD=''
            - JIBRI_RECORDER_USER=recorder
            - JIBRI_RECORDER_PASSWORD=''
        networks:
            meet.jitsi:
                aliases:
                    - meet.jitsi

    # XMPP server
    prosody:
        image: jitsi/prosody
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - /home/docker/.jitsi-meet-cfg/prosody:/config
        environment:
            - XMPP_DOMAIN=meet.jitsi
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_GUEST_DOMAIN=guest.meet.jitsi
            - XMPP_MUC_DOMAIN=muc.meet.jitsi
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
            - XMPP_RECORDER_DOMAIN=recorder.meet.jitsi
            - JICOFO_COMPONENT_SECRET=''
            - JICOFO_AUTH_USER=focus
            - JICOFO_AUTH_PASSWORD=''
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=''
            - JIGASI_XMPP_USER=jigasi
            - JIGASI_XMPP_PASSWORD=''
            - JIBRI_XMPP_USER=jibri
            - JIBRI_XMPP_PASSWORD=''
            - JIBRI_RECORDER_USER=recorder
            - JIBRI_RECORDER_PASSWORD=''
            - TZ=Europe/Amsterdam
        networks:
            meet.jitsi:
                aliases:
                    - xmpp.meet.jitsi

    # Focus component
    jicofo:
        image: jitsi/jicofo
        volumes:
            - /home/docker/.jitsi-meet-cfg/jicofo:/config
        environment:
            - XMPP_DOMAIN=meet.jitsi
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
            - JICOFO_COMPONENT_SECRET=''
            - JICOFO_AUTH_USER=focus
            - JICOFO_AUTH_PASSWORD=''
            - JVB_BREWERY_MUC=jvbbrewery
            - JIGASI_BREWERY_MUC=jigasibrewery
            - JIBRI_BREWERY_MUC=jibribrewery
            - JIBRI_PENDING_TIMEOUT=90
            - TZ=Europe/Amsterdam
        depends_on:
            - prosody
        networks:
            meet.jitsi:

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
            - '10000:10000/udp'
            - '4443:4443'
        volumes:
            - /home/docker/.jitsi-meet-cfg/jvb:/config
        environment:
            - XMPP_AUTH_DOMAIN=auth.meet.jitsi
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
            - XMPP_SERVER=xmpp.meet.jitsi
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=''
            - JVB_BREWERY_MUC=jvbbrewery
            - JVB_PORT=10000
            - JVB_TCP_HARVESTER_DISABLED=true
            - JVB_TCP_PORT=4443
            - JVB_STUN_SERVERS=meet-jit-si-turnrelay.jitsi.net:443
            - TZ=Europe/Amsterdam
        depends_on:
            - prosody
        networks:
            meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
```
, I get active services but with some errors.

<img width="1435" alt="Screenshot 2020-04-15 at 13 22 20" src="https://user-images.githubusercontent.com/8701039/79331934-3e582f80-7f1c-11ea-9351-6f7d94dbd8be.png">

<img width="974" alt="Screenshot 2020-04-15 at 13 16 24" src="https://user-images.githubusercontent.com/8701039/79331530-917db280-7f1b-11ea-8262-0405426ab364.png">

```
15/04/2020 13:16:25Exception in thread "main" org.jitsi.cmd.ParseException: Some of required arguments were not specified: [secret]
15/04/2020 13:16:25	at org.jitsi.cmd.CmdLine.parse(CmdLine.java:130)
15/04/2020 13:16:25	at org.jitsi.jicofo.Main.main(Main.java:118)
15/04/2020 13:16:26Jicofo 2020-04-15 13:16:26.170 WARNING: [1] org.jitsi.cmd.CmdLine.log() Skipped empty cmd line argument: host=
15/04/2020 13:16:26Jicofo 2020-04-15 13:16:26.174 WARNING: [1] org.jitsi.cmd.CmdLine.log() Skipped empty cmd line argument: secret=
15/04/2020 13:16:26Jicofo 2020-04-15 13:16:26.174 WARNING: [1] org.jitsi.cmd.CmdLine.log() Skipped empty cmd line argument: user_password=
```

<img width="1005" alt="Screenshot 2020-04-15 at 13 19 08" src="https://user-images.githubusercontent.com/8701039/79331603-ba05ac80-7f1b-11ea-90f1-1530ac321590.png">

```
15/04/2020 13:19:06Apr 15, 2020 1:19:06 PM org.jitsi.utils.logging2.LoggerImpl log
15/04/2020 13:19:06WARNING: [MucClient id=shard hostname=xmpp.meet.jitsi] error connecting
15/04/2020 13:19:06org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'xmpp.meet.jitsi:5222' failed because: java.net.UnknownHostException: xmpp.meet.jitsi: Name or service not known
15/04/2020 13:19:06	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
15/04/2020 13:19:06	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
15/04/2020 13:19:06	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
15/04/2020 13:19:06	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:383)
15/04/2020 13:19:06	at org.jitsi.xmpp.mucclient.MucClient.lambda$getConnectAndLoginCallable$7(MucClient.java:638)
15/04/2020 13:19:06	at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
15/04/2020 13:19:06	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
15/04/2020 13:19:06	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15/04/2020 13:19:06	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
15/04/2020 13:19:06	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
15/04/2020 13:19:06	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15/04/2020 13:19:06	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15/04/2020 13:19:06	at java.lang.Thread.run(Thread.java:748)
```

<img width="982" alt="Screenshot 2020-04-15 at 13 20 29" src="https://user-images.githubusercontent.com/8701039/79331716-e91c1e00-7f1b-11ea-9c87-6f112a01fb78.png">

```
15/04/2020 13:15:25saslauthd[227] :num_procs  : 5
15/04/2020 13:15:25saslauthd[227] :mech_option: /etc/saslauthd.conf
15/04/2020 13:15:25saslauthd[227] :run_path   : /var/run/saslauthd
15/04/2020 13:15:25saslauthd[227] :auth_mech  : ldap
15/04/2020 13:15:25saslauthd[227] :mmaped shared memory segment on file: /var/run/saslauthd/cache.mmap
15/04/2020 13:15:25saslauthd[227] :bucket size: 96 bytes
15/04/2020 13:15:25saslauthd[227] :stats size : 36 bytes
15/04/2020 13:15:25saslauthd[227] :timeout    : 28800 seconds
15/04/2020 13:15:25saslauthd[227] :cache table: 985828 total bytes
15/04/2020 13:15:25saslauthd[227] :cache table: 1711 slots
15/04/2020 13:15:25saslauthd[227] :cache table: 10266 buckets
15/04/2020 13:15:25saslauthd[227] :flock file opened at /var/run/saslauthd/cache.flock
15/04/2020 13:15:25saslauthd[227] :using accept lock file: /var/run/saslauthd/mux.accept
15/04/2020 13:15:25saslauthd[227] :master pid is: 0
15/04/2020 13:15:25saslauthd[227] :listening on socket: /var/run/saslauthd/mux
15/04/2020 13:15:25saslauthd[227] :using process model
15/04/2020 13:15:25saslauthd[227] :forked child: 245
15/04/2020 13:15:25saslauthd[245] :acquired accept lock
15/04/2020 13:15:25saslauthd[227] :forked child: 246
15/04/2020 13:15:25saslauthd[227] :forked child: 247
15/04/2020 13:15:25saslauthd[227] :forked child: 248
```

<img width="999" alt="Screenshot 2020-04-15 at 13 21 14" src="https://user-images.githubusercontent.com/8701039/79331776-0355fc00-7f1c-11ea-8f38-c302f0f00dda.png">

```
15/04/2020 13:21:02nginx: [emerg] host not found in upstream "xmpp.meet.jitsi" in /config/nginx/meet.conf:35
```

**Comment by colinvv2** [comment] 2020-04-25 15:54
I am struggling with this as well. Have you got it working yet?

**Comment by oprogramador** [comment] 2020-04-25 17:06
@colinvv2 

Not yet.
I've managed to fix something but later I got other errors.
You can like this issue (👍) so it'll be more likely that somebody will help.

**Comment by Echolon** [comment] 2020-06-19 21:11
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Comment by Echolon** [comment] 2020-06-19 21:13
Hmm sorry, I will keep this open.

**Comment by progressify** [comment] 2021-02-09 12:34
same for me
but @oprogramador you haven't used the file `gen-password.sh` for generating random password in `.env` file.
you put directly the env var values in your compose file. and you haven't set a value for `JICOFO_COMPONENT_SECRET=''`. I think it is required.

**Comment by oprogramador** [comment] 2021-02-09 13:00
I don't know.

Maybe, it's required.

Anyway, I don't need Jitsi for now.

**Comment by saghul** [comment] 2021-02-09 13:13
Many things have changed since, @progressify please open a new issue, let's stay out of @oprogramador 's notifications :-)

**Closed by saghul** 2021-02-09 13:13 UTC
Labels: question
