### ISSUE TITLE
Jitsi-meet with LDAP authentication does not work if user name is a full email address

### ISSUE THREAD

**Issue by volo-zyko** [jitsi/docker-jitsi-meet#173] opened 2020-01-22 23:26 UTC
I spent two days trying to figure this out. Jitsi-meet worked fine for anonymous users. `testsaslauthd` worked successfully in the prosody docker container. There were no any errors in the `docker-compose logs`. The only thing I found by the end of my investigation is an error in the browser console - "Strophe: Server did not offer a supported authentication mechanism" and then "Unauthorized to start the conference" with `textContent` "not authorized user domain".

It happens that my LDAP server identifies users by their email addresses. But such IDs are silently rejected along the way to prosody.

For now, my instance of Jitsi-meet authenticates users with `LDAP_FILTER=(mail=%u@my.domain1)` configuration and users omit `@my.domain1` part at login. However, not clear what I should do now with users in `my.domain2`, etc.

**Comment by saghul** [comment] 2020-01-23 09:46
@netaskd any ideas?

**Comment by netaskd** [comment] 2020-01-23 17:16
Hard to say without looking into configuration. If `testsaslauthd` works, ldap requests works properly.
I guess the error "not authorized user domain" about XMPP domain that were configured in `XMPP_AUTH_DOMAIN`, `XMPP_AUTH_DOMAIN` and so on.

For filtering users in different domains try to use `LDAP_FILTER=(|(mail=%u@my.domain1)(mail=%u@my.domain2))`
about ldap syntax you can read here: http://www.ldapexplorer.com/en/manual/109010000-ldap-filter-syntax.htm

**Comment by volo-zyko** [comment] 2020-01-23 18:20
Here is my [.env](https://gist.github.com/volo-zyko/18e458e0d552c8fcf41d5adc69c75167) file.

**Comment by volo-zyko** [comment] 2020-01-24 22:07
Well, now I better understand the issue and I want to record this, so people may benefit from it.

LDAP authentication with `LDAP_FILTER=(mail=%u)` doesn't work if the user's email address is not in the same domain as `XMPP_DOMAIN`. Or vise versa if `XMPP_DOMAIN` is `external.fqdn` and user's email looks like `user1@external.fqdn` then authentication with full email address works, otherwise better use only `user1` part as login name and `LDAP_FILTER` must be a bit more complicated as suggested by @netaskd.

**Comment by MaxNoe** [comment] 2020-03-26 18:56
Ok, that is quite sad, because we especially want external users to be able to login via email, so they don't have to memorize a username.

**Comment by MaxNoe** [comment] 2020-03-26 18:57
So what is the actual value of `%u`? Is it not what the user entered in the username field? That would be highly surprising to me. Where does additional stuff get added to this?

**Comment by volo-zyko** [comment] 2020-03-26 20:25
As recorded in the `.env` file above the `LDAP_FILTER` is `(mail=%u@external.fqdn)`. So, `%u` is indeed what user entered and in `LDAP_FILTER` the rest is added.

**Comment by MaxNoe** [comment] 2020-03-26 21:23
Ok, so logging in with Email is just broken at the moment and you worked around it by adding @tld in your ldap filter?

That's not going to work for us, as we'd especially like the email login for external users so they don't have to remember a username.

All our internal users us usernames anyways as it's less to type

**Comment by netaskd** [comment] 2020-03-26 21:57
@MaxNoe try to use filter like (mail=%U@%d)
More info here https://blog.sys4.de/cyrus-sasl-saslauthdconf-man-page-en.html

**Comment by MaxNoe** [comment] 2020-03-27 06:09
@netaskd Tried that, still not working. I think the Problem is with this #303, it never even reaches the saslauth stack

**Comment by MaxNoe** [comment] 2020-03-27 06:11
@netaskd I tried with `testsaslauth` in the container, that works. But not through the webinterface:

```
$ testsaslauthd -u <email> -p $(read -s pwd; echo $pwd)
```

**Comment by joker-x** [comment] 2020-04-02 02:34
A workaround:

Yo can change the function toJid https://github.com/jitsi/jitsi-meet/blob/7684b2bf98a9b7f9fe719f8ffe86e968370ec523/react/features/base/connection/functions.js#L132 from:
```js
export function toJid(id: string, { authdomain, domain }: Object): string {
    return id.indexOf('@') >= 0 ? id : `${id}@${authdomain || domain}`;
}
```

to:
```js
export function toJid(id: string, { authdomain, domain }: Object): string {
    return `${id.split('@').join('.at.')}@${authdomain || domain}`;
}
```

Later, in /usr/lib/prosody/modules/mod_auth_ldap2/mod_auth_ldap2.lua change from:
```lua
function provider.test_password(username, password)
    return ldap.bind(username, password);
end
```
To
```lua
function provider.test_password(username, password)
    local username = string.gsub(username, '.at.', '@');
    return ldap.bind(username, password);
end
```

And restart prosody.

Now in website can be login with email in LDAP and with the official mobile clients have to replace @ for .at.

**Comment by sooslaca** [comment] 2020-05-07 12:58
@joker-x By any chance would you know what you needs to be patched for fix prosody auth for saslauthd?

**Comment by johan-smits** [comment] 2020-05-07 17:17
@sooslaca you can set the `XMPP_DOMAIN` to the same domain as you try to use for the email to login.

In my case we only have 1 email domain so this is possible. But if there are multiple domains it will not work.

Example:

`XMPP_DOMAIN` = `domain1.com`

Now I can login with: `foo@domain1.com`
Also with: `foo`
But __not__ with `bla@domain2.com`

**Comment by sooslaca** [comment] 2020-05-07 18:16
Gotcha, thx, unfortunately I’d love to use multiple domains

**Comment by Allen-yan** [comment] 2021-01-11 08:43
@johan-smits  where can I find the XMPP_DOMAIN config

**Comment by johan-smits** [comment] 2021-01-11 09:21
@Allen-yan It is in the documentation: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#advanced-configuration

**Comment by lavdnone** [comment] 2022-05-03 17:21
adding @joker-x 
### to be able to use email or usernames with @ for jitsi meet
if using docker or don't want to remake below sed will change react/features/base/connection/functions.js in short version app.bundle.min.js
```
sed -i 's/return e.indexOf(\"@\")>=0?e:`${e/return\`${e.split(\"@\").join(\".at.\")/' /usr/share/jitsi-meet/libs/app.bundle.min.js
```

and whichever auth lua module you use need to escape . dots in gsub,
```
local username = string.gsub(username, "%.at%.", "@");
```

**Comment by saghul** [comment] 2022-05-04 07:45
I'm closing this. There are a couple of workarounds, but alas we can't support this out of the box because of the other auth backends.

**Closed by saghul** 2022-05-04 07:45 UTC

**Comment by bojidar-bg** [comment] 2024-08-02 14:12
To get the workaround from the above working for Cyrus SASL:
```
sed -E -i 's/local node = s_match\(user, "\^\(\[\^@\]\+\)"\);/local node = s_gsub(user, "%.at%.", "@");/;/local pcall = pcall/a local s_gsub = string.gsub' /prosody-plugins/sasl_cyrus.lua

sed -i 's/session.sasl_handler.username/string.gsub(session.sasl_handler.username, "@", ".at.")/' /usr/lib/prosody/modules/mod_saslauth.lua
```

(it was quite a pain to figure out, and XMPP hating usernames with @ symbols in them didn't help either, but it would be nice to have the solution at least documented better. Most other applications using LDAP will directly send whatever is in the input field to LDAP, but Jitsi/Prosody being different is never hinted at in either software's documentation.)
