### ISSUE TITLE
Not merging A/V streams with 3 participants and more. 

### ISSUE THREAD

**Issue by tux1980** [jitsi/docker-jitsi-meet#646] opened 2020-06-16 19:53 UTC
Hi!
I have a challenge... As soon as 3+ People enter the room Audio and Video is disappearing. The JVB Service/Container is obviously fine. I can reach the STUN servers and, no errors at all in the log. B

ut there is some message in the jicofo log, always when 3 third member is entering the room. . 

**jicofo Log is stating "Not merging A/V Streams":**
org.jitsi.jicofo.LipSyncHack.log() Not merging A/V streams from wolli@muc.meet-wolli-office.apps.ocp4.kimmlingen.org/18d47bc8 to wolli@muc.meet-wolli-office.apps.ocp4.kimmlingen.org/15d74912

Any Idea on the Topic?

Thanks!
Wolfgang

**Comment by Echolon** [comment] 2020-06-19 20:46
Hi,

I think this is a duplicate of 

**3-way audio/video call is not happening** #606 

Anyway, thank you for your efforts. Those are very appreciated!

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-06-19 20:46 UTC
