### ISSUE TITLE
Azure kubernetes setup issue

### ISSUE THREAD

**Issue by vnvbadri** [jitsi/docker-jitsi-meet#649] opened 2020-06-17 16:53 UTC
hi we have jitsi standalone setup configured in Ubuntu16 which is working fine. now we wanted to setup in azure kubernetes, i have followed https://github.com/jitsi/docker-jitsi-meet/tree/master/examples/kubernetes for setup. we are facing issue in configuration.

we are getting “bridge channel send: no opened channel” error i have searched in community where i found this issue is related to DOCKER_HOST_ADDRESS in deployment file. but in azure kubernetes there will no host for master(it works as service), so how can i set docker host address, i tried adding public ip but still no luck

also any setup articles available for azure kubernetes

**Comment by marksel** [comment] 2020-07-21 14:09
What is your exact issue?
I have an Azure set up running.

If you are using something like nginx ingress to forward the 10000 / 4443 port to the service you can use:
`            - name: DOCKER_HOST_ADDRESS
              value: '13.81.241.147'
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
`
Otherwise you can use something like a loadbalancer or have your ip + port public and use that ip address

**Comment by Echolon** [comment] 2020-07-29 16:15
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org

Unfortunately, I have to close this :(

You can improve you issue by using the template. Then I can reopen.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*

**Closed by Echolon** 2020-07-29 16:15 UTC
Labels: question
